# Generated by Django 3.1.4 on 2020-12-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_addstory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddStory',
            new_name='Story',
        ),
    ]
