# Generated by Django 3.1.4 on 2020-12-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20201222_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
