# Generated by Django 3.1.4 on 2020-12-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_story_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='photo',
        ),
    ]
